### ISSUE TITLE
code: 'ERR_INVALID_ARG_TYPE'

### ISSUE THREAD

**Issue by bfraiman** [chidimo/Fireact#10]
When I run yarn startdev i have this issue:

yarn run v1.22.10
$ nodemon --exec babel-node ./src/bin/www
[nodemon] 2.0.7
[nodemon] reading config ./nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 93575 to restart
[nodemon] ignoring: *.test.js *.spec.js
[nodemon] watching path(s): .env package.json nodemon.json .eslintrc.json .babelrc src/**/*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `babel-node ./src/bin/www.js`
[nodemon] spawning
[nodemon] child pid: 93581
[nodemon] watching 20 files
node:internal/validators:129
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:329:5)
    at validateString (node:internal/validators:129:11)
    at Module.require (node:internal/modules/cjs/loader:988:3)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/bfraiman/Desktop/Workspace/admin/example/packages/server/src/firebaseInit.js:5:24)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Module._compile (/Users/bfraiman/Desktop/Workspace/admin/example/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Object.newLoader [as .js] (/Users/bfraiman/Desktop/Workspace/admin/example/node_modules/pirates/lib/index.js:104:7)
    at Module.load (node:internal/modules/cjs/loader:971:32) {
  code: 'ERR_INVALID_ARG_TYPE'
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by wasif-ahmed** [comment]
facing same issue, has any one found the solution?
